# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-19 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=45)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('plan', models.TextField()),
                ('attendees', models.ManyToManyField(related_name='trips', to='log_app.User')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='log_app.User')),
            ],
        ),
    ]
