# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-19 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190419_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip', to='log_app.User'),
        ),
    ]
